name: Continuous Deployment

on:
  workflow_run:
    workflows: ['Continuous Integrations']
    types:
      - completed

  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push --force https://quangtn266:$HF_TOKEN@huggingface.co/spaces/quangtn266/Drug-Classification main
