name: Continuous Deployment

on:
  workflow_run:
    workflows: ['Continuous Integrations']
    types:
      - completed

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: iterative/setup-cml@v2
        with:
          version: 'v0.20.0'
          vega: false

      - name: Deployment to HuggingFace
        env:
          HF: ${{ secrets.HF_TOKEN }}
        run: make deploy HF=$HF
