name: Continuous Deployment

on:
  workflow_run:
    workflows: ['Continuous Integrations']
    types:
      - completed

  workflow_dispatch:

#jobs:
#  build:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - uses: iterative/setup-cml@v2
#        with:
#          version: 'v0.20.0'
#          vega: false

 #     - name: Deployment to HuggingFace
 #       env:
 #         HF_TOKEN: ${{ secrets.HF_TOKEN }}
 #       run: make deploy HF=$HF_TOKEN

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push --force https://quangtn266:$HF_TOKEN@huggingface.co/spaces/quangtn266/Drug-Classification main
